import { StyleSheet } from "react-native"; 

 export const design = StyleSheet.create({
    body: {
        backgroundColor: 'white',
        width: '100%',
        height: 'auto',
        paddingLeft: 20,
        paddingRight: 20,
        paddingTop: 50,
        paddingBottom: 70,
    },
    chechTick: {
        fontSize: 20,
    },
    signdiv: {
        backgroundColor: 'white',
        width: '100%',
        alignItems: 'center',
        marginTop: 20,
    },
    signin: {
        fontSize: 25,
        color: 'black',
    },
    welcome: {
        color: '#7C7C7C',
        marginTop: 5,
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
    },
    divEnvelope: {
        backgroundColor: '#F7F7F7',
        marginTop: 40,
        height: 60,
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    iconTouch: {
        backgroundColor: '#F8D3FE',
        width: '10%',
        height: 30,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        position: 'absolute',
        marginLeft: 10,
    },
    envelopeIcon: {
        fontSize: 20,
        color: '#EB86FD',
    },
    input: {
        borderWidth: 1,
        borderColor: 'black',
        borderRadius: 15,
        height: '100%',
        width: '100%',
        paddingLeft: 53,
    },
    div2Envelope: {
        backgroundColor: '#F7F7F7',
        marginTop: 20,
        height: 60,
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    lockTouch: {
        backgroundColor: '#E1EAFF',
        width: '10%',
        height: 30,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        position: 'absolute',
        marginLeft: 10,
    },
    lockIcon: {
        fontSize: 20,
        color: '#82A4FF',
    },
    checkboxDiv: {
        backgroundColor: 'white',
        width: '100%',
        height: 60,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        gap: -5,
    },
    checkContainer: {
        marginLeft: 0,  
        marginRight: 10,  
        padding: 0,  
        borderWidth: 0,
        backgroundColor: 'transparent',
    },
    rememberMe: {
        marginLeft: 5,
    },
    blue: {
        backgroundColor: 'white',
        width: '100%',
        height: 'auto',
        marginTop: 100,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 20,
    },
    forgotTouch: {
        width: 'auto',
        height: 20,
        backgroundColor: 'white',
    },
    forgotPassword: {
        fontSize: 15,
        color: '#119BFF',
    },
    signinbtn: {
        width: '100%',
        backgroundColor: '#119BFF',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
        borderRadius: 30,
    },
    signinWord: {
        color: 'white',
        fontSize: 20,
    },
    createDiv: {
        backgroundColor: 'white',
        marginTop: 20,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    createSignup: {
        width: '20%',
        borderRadius: 10,
        backgroundColor: '#F7F7F7',
        alignItems: 'center',
    },
    signup: {
        color: '#FEBD4E',
    },
    bottomIcons: {
        backgroundColor: 'white',
        marginTop: 80,
        width: '100%',
        height: 'auto',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    fbTouch: {
        width: '10%',
        height: 30,
        alignItems: 'center',
        display:'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#F7F7F7',
        borderRadius: 30,
    },
    fb: {
        color: '#216CD3',
        fontSize: 20,
    },
    google: {
        color: '#EA523D',
        fontSize: 20,
    },
    apple: {
        color: '#15131E',
        fontSize: 20,
    }
})